# Generated by Django 5.1 on 2024-08-22 20:37

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    operations = [
        VectorExtension()
    ]
