# Generated by Django 5.1 on 2024-08-22 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_remove_patentclaim_claim_text_patentclaim_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="claimelement",
            old_name="element_text",
            new_name="text",
        ),
    ]
