# Generated by Django 5.1 on 2024-08-23 19:04

from django.db import migrations


def populate_mod_type768(apps, schema_editor):
    ThisModel = apps.get_model('polls', 'embedding768')
    DocModel = apps.get_model('polls', 'SectionEmbedding')
    ClaimModel = apps.get_model('polls', 'ClaimEmbedding')

    for index, obj in enumerate(ThisModel.objects.all(), start=1):
        if index % 100 == 0:
            print(f"Processing mod type 768 {index}")
        embed_id = obj.embed_id
        if obj.embed_source == 'document':
            embedding_model = DocModel
        elif obj.embed_source == 'claim':
            embedding_model = ClaimModel
        else:
            raise ValueError(f"'{obj.embed_source}' is not a valid source type.")

        embed_obj = embedding_model.objects.get(id=embed_id)
        obj.mod_type_name = embed_obj.source.modification_type.name
        print(f"Setting {index} {obj.orig_source_id} to {obj.mod_type_name}")
        obj.save()


def populate_mod_type32(apps, schema_editor):
    ThisModel = apps.get_model('polls', 'embedding32')
    DocModel = apps.get_model('polls', 'SectionEmbedding')
    ClaimModel = apps.get_model('polls', 'ClaimEmbedding')

    for index, obj in enumerate(ThisModel.objects.all(), start=1):
        if index % 100 == 0:
            print(f"Processing mod type 32 {index}")
        embed_id = obj.embed_id
        if obj.embed_source == 'document':
            embedding_model = DocModel
        elif obj.embed_source == 'claim':
            embedding_model = ClaimModel
        else:
            raise ValueError(f"'{obj.embed_source}' is not a valid source type.")

        embed_obj = embedding_model.objects.get(id=embed_id)
        obj.mod_type_name = embed_obj.source.modification_type.name
        print(f"Setting {index} {obj.orig_source_id} to {obj.mod_type_name}")
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_embedding32_mod_type_name_embedding768_mod_type_name"),
    ]

    operations = [
        migrations.RunPython(populate_mod_type768),
        migrations.RunPython(populate_mod_type32),
    ]
