# Generated by Django 5.1 on 2024-08-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0006_auto_20240823_1904"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimforembedding",
            name="openai_tokens",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sectionforembedding",
            name="openai_tokens",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
