# Generated by Django 5.1 on 2024-09-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0008_auto_20240824_2136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionforembedding",
            name="openai_tokens",
            field=models.IntegerField(null=True),
        ),
    ]
