# Generated by Django 5.1 on 2024-09-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0009_alter_sectionforembedding_openai_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docsection",
            name="section_title",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="docsection",
            name="section_title_text",
            field=models.TextField(default=""),
        ),
    ]
