# Generated by Django 5.1 on 2024-09-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0010_alter_docsection_section_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docsection",
            name="section_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="embedding32",
            name="embed_type_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="embedding32",
            name="mod_type_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="embedding768",
            name="embed_type_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="embedding768",
            name="mod_type_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="embeddingtype",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="modificationtype",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="patent",
            name="patent_country",
            field=models.CharField(max_length=10),
        ),
    ]
