# Generated by Django 5.1 on 2024-10-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0011_alter_docsection_section_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingtype",
            name="short_name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
