# Generated by Django 5.1 on 2024-10-01 20:42

from django.db import migrations


def populate_shortname(apps, schema_editor):
    # Define your mapping of field1 to field2 values
    field_mapping = {
        'TOPIC_MODEL_VIDEO COMPRESSION - block': 'tpm_vc_block',
        'DIGITAL_VIDEO_TPM - parameter': 'tpm_dv_param',
        'PATENT_SBERT':   'psbert',
    }

    EmbedModel = apps.get_model('polls', 'Embedding32')

    for instance in EmbedModel.objects.all():
        if instance.embed_type_name in field_mapping:
            instance.embed_type_shortname = field_mapping[instance.embed_type_name]
            instance.save()

    EmbedModel = apps.get_model('polls', 'Embedding768')

    for instance in EmbedModel.objects.all():
        if instance.embed_type_name in field_mapping:
            instance.embed_type_shortname = field_mapping[instance.embed_type_name]
            instance.save()


def reverse_func(apps, schema_editor):

    EmbedModel = apps.get_model('polls', 'Embedding32')
    EmbedModel.objects.all().update(embed_type_shortname=None)

    EmbedModel = apps.get_model('polls', 'Embedding768')
    EmbedModel.objects.all().update(embed_type_shortname=None)


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0013_embedding32_embed_type_shortname_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_shortname, reverse_func),
    ]
