# Generated by Django 5.1 on 2024-10-03 04:34

from django.db import migrations


def populate_filename(apps, scheme_editor):

    DocumentModel = apps.get_model('polls', 'Document')
    for instance in DocumentModel.objects.filter(filename="NA"):
        instance.filname = instance.name


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0015_document_filename"),
    ]

    operations = [
        migrations.RunPython(populate_filename),
    ]
