# Generated by Django 5.1 on 2024-10-25 20:36

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0017_claimrelatedsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Embedding1536",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embed_source",
                    models.CharField(
                        help_text="Indicates whether the embedding is for a claim or document",
                        max_length=10,
                    ),
                ),
                (
                    "embed_id",
                    models.BigIntegerField(
                        help_text="ID in the respective table for the claim/document Embedding"
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        help_text="ID to the document/claim xxForEmbedding) record that has text that used for embeddning"
                    ),
                ),
                (
                    "orig_source_id",
                    models.BigIntegerField(
                        help_text="ID to the document/claim record that has the original source text in the documents (before any modifications)"
                    ),
                ),
                ("embed_type_name", models.CharField(max_length=200)),
                ("mod_type_name", models.CharField(max_length=200)),
                ("embed_type_shortname", models.CharField(max_length=20, null=True)),
                (
                    "embedding_vector",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="1536 element Vector embedding",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
