# Generated by Django 5.1 on 2024-10-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0019_rename_sectionforembedding_modifieddocsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedding1536",
            name="chunk_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="embedding1536",
            name="total_chunks",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="embedding32",
            name="chunk_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="embedding32",
            name="total_chunks",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="embedding768",
            name="chunk_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="embedding768",
            name="total_chunks",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="embeddingtype",
            name="windows_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sectionembedding",
            name="total_chunks",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="embedding1536",
            name="embed_id",
            field=models.BigIntegerField(
                help_text="ID in (Claim Embedding/Section Embeding) table that indicates the modified text and embedding type  "
            ),
        ),
        migrations.AlterField(
            model_name="embedding1536",
            name="orig_source_id",
            field=models.BigIntegerField(
                help_text="ID to the (doc/claim) record that has the original source text in the documents (before any modifications)"
            ),
        ),
        migrations.AlterField(
            model_name="embedding1536",
            name="source_id",
            field=models.BigIntegerField(
                help_text="ID to the document/claim xxForEmbedding) record that text to be used for embeddning (after modificaitons, before chunking)"
            ),
        ),
        migrations.AlterField(
            model_name="embedding32",
            name="embed_id",
            field=models.BigIntegerField(
                help_text="ID in (Claim Embedding/Section Embeding) table that indicates the modified text and embedding type  "
            ),
        ),
        migrations.AlterField(
            model_name="embedding32",
            name="orig_source_id",
            field=models.BigIntegerField(
                help_text="ID to the (doc/claim) record that has the original source text in the documents (before any modifications)"
            ),
        ),
        migrations.AlterField(
            model_name="embedding32",
            name="source_id",
            field=models.BigIntegerField(
                help_text="ID to the document/claim xxForEmbedding) record that text to be used for embeddning (after modificaitons, before chunking)"
            ),
        ),
        migrations.AlterField(
            model_name="embedding768",
            name="embed_id",
            field=models.BigIntegerField(
                help_text="ID in (Claim Embedding/Section Embeding) table that indicates the modified text and embedding type  "
            ),
        ),
        migrations.AlterField(
            model_name="embedding768",
            name="orig_source_id",
            field=models.BigIntegerField(
                help_text="ID to the (doc/claim) record that has the original source text in the documents (before any modifications)"
            ),
        ),
        migrations.AlterField(
            model_name="embedding768",
            name="source_id",
            field=models.BigIntegerField(
                help_text="ID to the document/claim xxForEmbedding) record that text to be used for embeddning (after modificaitons, before chunking)"
            ),
        ),
        migrations.CreateModel(
            name="ModifiedSectionChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_number", models.IntegerField()),
                ("chunk_text", models.TextField()),
                (
                    "modified_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.modifieddocsection",
                    ),
                ),
                (
                    "section_embedding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.sectionembedding",
                    ),
                ),
            ],
        ),
    ]
