# Generated by Django 5.1 on 2024-10-30 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0020_embedding1536_chunk_number_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClaimForEmbedding",
            new_name="ModifiedClaim",
        ),
        migrations.RenameModel(
            old_name="ModifiedDocSection",
            new_name="ModifiedSection",
        ),
        migrations.RenameModel(
            old_name="DocSection",
            new_name="Section",
        ),
    ]
