# Generated by Django 5.1 on 2024-10-30 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0021_rename_claimforembedding_modifiedclaim_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClaimEmbedding",
            new_name="ClaimChunkInfo",
        ),
        migrations.RenameModel(
            old_name="SectionEmbedding",
            new_name="SectionChunkInfo",
        ),
        migrations.RemoveField(
            model_name="modifiedsection",
            name="openai_tokens",
        ),
    ]
