# Generated by Django 5.1 on 2024-10-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0022_rename_claimembedding_claimchunkinfo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimchunkinfo",
            name="total_chunks",
            field=models.IntegerField(default=1),
        ),
    ]
