# Generated by Django 5.1 on 2024-11-02 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0025_rename_section_modifiedsection_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modifiedsectionchunk",
            old_name="section_embedding",
            new_name="item_embedding",
        ),
    ]
