# Generated by Django 5.1 on 2024-11-02 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0026_rename_section_embedding_modifiedsectionchunk_item_embedding"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modifiedclaim",
            old_name="claim",
            new_name="item",
        ),
    ]
