# Generated by Django 5.1 on 2024-11-02 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0027_rename_claim_modifiedclaim_item"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ModifiedClainChunk",
            new_name="ModifiedClaimChunk",
        ),
    ]
