# Generated by Django 5.1 on 2024-11-03 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0028_rename_modifiedclainchunk_modifiedclaimchunk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modifiedsectionchunk",
            old_name="item_embedding",
            new_name="chunk_info",
        ),
    ]
