# Generated by Django 5.1 on 2024-11-03 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0029_rename_item_embedding_modifiedsectionchunk_chunk_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="embedding1536",
            old_name="embed_id",
            new_name="chunk_info_id",
        ),
        migrations.RenameField(
            model_name="embedding32",
            old_name="embed_id",
            new_name="chunk_info_id",
        ),
        migrations.RenameField(
            model_name="embedding768",
            old_name="embed_id",
            new_name="chunk_info_id",
        ),
    ]
