# Generated by Django 5.1 on 2024-11-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0030_rename_embed_id_embedding1536_chunk_info_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modifiedclaim",
            name="openai_tokens",
        ),
        migrations.AlterField(
            model_name="embedding1536",
            name="chunk_info_id",
            field=models.BigIntegerField(
                help_text="ID in ChunkInfo table (Claim/Section ChunkInfo) that indicates the modified text and embedding type."
            ),
        ),
        migrations.AlterField(
            model_name="embedding32",
            name="chunk_info_id",
            field=models.BigIntegerField(
                help_text="ID in ChunkInfo table (Claim/Section ChunkInfo) that indicates the modified text and embedding type."
            ),
        ),
        migrations.AlterField(
            model_name="embedding768",
            name="chunk_info_id",
            field=models.BigIntegerField(
                help_text="ID in ChunkInfo table (Claim/Section ChunkInfo) that indicates the modified text and embedding type."
            ),
        ),
    ]
