# Generated by Django 5.1.2 on 2024-11-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0032_tag_embedding1536_tags_embedding32_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddingtype",
            name="short_name",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
