# Generated by Django 5.1.2 on 2024-11-16 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0033_alter_embeddingtype_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedding1536",
            name="embed_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.embeddingtype",
            ),
        ),
        migrations.AddField(
            model_name="embedding32",
            name="embed_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.embeddingtype",
            ),
        ),
        migrations.AddField(
            model_name="embedding768",
            name="embed_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.embeddingtype",
            ),
        ),
        migrations.AlterField(
            model_name="embedding1536",
            name="embed_type_shortname",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="embedding32",
            name="embed_type_shortname",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="embedding768",
            name="embed_type_shortname",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
